const ROOT_SWAP_PAIR_CONTRACT_TYPE = 0;
const SWAP_PAIR_CONTRACT_TYPE = 1;
const SWAP_EVENT_ID = 0;
const PROVIDE_LIQUIDITY_EVENT_ID = 1;
const WITHDRAW_LIQUIDITY_EVENT_ID = 2;

module.exports = {
    ROOT_SWAP_PAIR_CONTRACT_TYPE,
    SWAP_PAIR_CONTRACT_TYPE,
    SWAP_EVENT_ID,
    PROVIDE_LIQUIDITY_EVENT_ID,
    WITHDRAW_LIQUIDITY_EVENT_ID
}